name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml"]
  pull_request:
    branches: ["*"]
    paths: ["**/*.rs", "**/Cargo.toml"]

  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo_test:
    runs-on: self-hosted
    steps:
      - uses: getsynth/checkout@v2
      - uses: getsynth/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --all-features -- --nocapture
